### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by jeffclay** [weltlink/django-quickbooks#12]
Hi, this project looks great and seems to be exactly what I'm looking for. However, I am curious about stability. Is the project as a whole ready for production use? Are the QB Desktop features ready for production use?

Thanks!

**Comment by bedilbek** [comment]
Hi @jeffclay, thanks for your interest in the project.

I am not sure about its robust stability, because I am using it only for several months with not a big audience of usage, but at least it was working fine with one exception. 

I implemented RabbitMQ as a QueueManager for interconnection between the project and Quickbooks Desktop in the wrong way. Thus, connection was being lost time by time and I had to restart the server (issue is present until release 0.6.4.2 including). Then, recently I refactored most of the logic (without backward compatability) and added Redis as a new QueueManager implementation. Most probably thinking of releasing version 1.0, maybe starting from this release it will become stable and backward compatibility will be kept. However, unless version 1.0 is released, you can try the `master` branch with latest updates.
